# Generated by Django 3.0 on 2020-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='folder',
        ),
        migrations.AddField(
            model_name='files',
            name='is_file',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='parent_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
