# Generated by Django 3.0 on 2020-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_structure', '0002_auto_20200103_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
